
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.0

services:
  - docker

stages:
  - name: test
  - name: pack
    if: type != pull_request AND branch = master

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: test
      script:
        - make test
    - stage: pack
      script:
        - make pack
