language: csharp
sudo: required
dist: trusty
mono: none
dotnet: latest
env:
  - CLI_VERSION=latest
  - TEST_DIR=test/SprayChronicle.CommandHandling.Test
  - TEST_DIR=test/SprayChronicle.EventHandling.Test
  - TEST_DIR=test/SprayChronicle.EventSourcing.Test
  - TEST_DIR=test/SprayChronicle.Example.Test
  - TEST_DIR=test/SprayChronicle.MessageHandling.Test
  - TEST_DIR=test/SprayChronicle.Persistence.Ouro.Test
  - TEST_DIR=test/SprayChronicle.QueryHandling.Test
  - TEST_DIR=test/SprayChronicle.Server.Http.Test
  - TEST_DIR=test/SprayChronicle.Testing.Test
  - PACK_DIR=src/SprayChronicle.CommandHandling
  - PACK_DIR=src/SprayChronicle.EventHandling
  - PACK_DIR=src/SprayChronicle.EventSourcing
  - PACK_DIR=src/SprayChronicle.MessageHandling
  - PACK_DIR=src/SprayChronicle.Persistence.Memory
  - PACK_DIR=src/SprayChronicle.Persistence.Mongo
  - PACK_DIR=src/SprayChronicle.Persistence.Ouro
  - PACK_DIR=src/SprayChronicle.Projecting
  - PACK_DIR=src/SprayChronicle.QueryHandling
  - PACK_DIR=src/SprayChronicle.Server
  - PACK_DIR=src/SprayChronicle.Server.Http
  - PACK_DIR=src/SprayChronicle.Testing
script:
  - cd $PACK_DIR && dotnet restore
  - cd $TEST_DIR && dotnet restore
  - cd $TEST_DIR && dotnet test
  - cd $PACK_DIR && dotnet pack -c Release --version-suffix build-$TRAVIS_BUILD_NUMBER --include-symbols --output SprayChronicle.nupkg
  - cd $PACK_DIR && dotnet nuget push SprayChronicle.nupkg --api-key $NUGET_KEY
