language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.1
env:
  - PACKAGE=SprayChronicle.CommandHandling
  - PACKAGE=SprayChronicle.EventHandling
  - PACKAGE=SprayChronicle.EventSourcing
  - PACKAGE=SprayChronicle.MessageHandling
  - PACKAGE=SprayChronicle.Persistence.Memory
  - PACKAGE=SprayChronicle.Persistence.Mongo
  - PACKAGE=SprayChronicle.Persistence.Ouro
  - PACKAGE=SprayChronicle.Projecting
  - PACKAGE=SprayChronicle.QueryHandling
  - PACKAGE=SprayChronicle.Server
  - PACKAGE=SprayChronicle.Server.Http
  - PACKAGE=SprayChronicle.Testing
install:
  - cd $TRAVIS_BUILD_DIR/src/$PACKAGE && dotnet restore
  - cd $TRAVIS_BUILD_DIR/test/$PACKAGE.Test && dotnet restore
script:
  - cd $TRAVIS_BUILD_DIR/test/$PACKAGE.Test && dotnet test
after_script:
  - cd $TRAVIS_BUILD_DIR/src/$PACKAGE && dotnet pack -c Release --version-suffix build-$TRAVIS_BUILD_NUMBER --include-symbols --output $PACKAGE.nupkg && dotnet nuget push $PACKAGE.nupkg --api-key $NUGET_KEY -s https://www.nuget.org/api/v2/package
