language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.1
env:
  - PACKAGE=SprayChronicle.CommandHandling
  - PACKAGE=SprayChronicle.EventHandling
  - PACKAGE=SprayChronicle.EventSourcing
  - PACKAGE=SprayChronicle.MessageHandling
  - PACKAGE=SprayChronicle.Persistence.Memory
  - PACKAGE=SprayChronicle.Persistence.Mongo
  - PACKAGE=SprayChronicle.Persistence.Ouro
  - PACKAGE=SprayChronicle.Projecting
  - PACKAGE=SprayChronicle.QueryHandling
  - PACKAGE=SprayChronicle.Server
  - PACKAGE=SprayChronicle.Server.Http
  - PACKAGE=SprayChronicle.Testing
install:
  - cd src/$PACKAGE && dotnet restore
  - cd test/$PACKAGE.Test && dotnet restore
script:
  - test/$PACKAGE.Test && dotnet test
deploy:
  - src/$PACKAGE && dotnet pack -c Release --version-suffix build-$TRAVIS_BUILD_NUMBER --include-symbols --output SprayChronicle.nupkg && dotnet nuget push SprayChronicle.nupkg --api-key $NUGET_KEY
