version: '3.3'

services:
  commandhandling:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.CommandHandling.Test
    entrypoint: dotnet 
    command: test
    
  eventhandling:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.EventHandling.Test
    entrypoint: dotnet
    command: test

  eventsourcing:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.EventSourcing.Test
    entrypoint: dotnet
    command: test

  example:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Example.Test
    entrypoint: dotnet
    command: test

  messagehandling:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.MessageHandling.Test
    entrypoint: dotnet
    command: test

  persistence_mongo:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Persistence.Mongo.Test
    entrypoint: dotnet
    command: test

  persistence_ouro:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Persistence.Ouro.Test
    depends_on:
      - eventstore
    environment:
      - EVENTSTORE_HOST=eventstore
    entrypoint: dotnet
    command: test

  persistence_raven:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Persistence.Raven.Test
    depends_on:
      - ravendb
    environment:
      - RAVENDB_HOST=http://ravendb:8080
    entrypoint: dotnet
    command: test

  queryhandling:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.QueryHandling.Test
    entrypoint: dotnet
    command: test

  server:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Server.Test
    entrypoint: dotnet
    command: test

  server_http:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Server.Http.Test
    entrypoint: dotnet
    command: test

  testing:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Testing.Test
    entrypoint: dotnet test
    command: test

  eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_MEM_DB=1
      - EVENTSTORE_START_STANDARD_PROJECTIONS=1
      - EVENTSTORE_RUN_PROJECTIONS=All
    ports:
      - 1113:1113
      - 2113:2113

  ravendb:
    image: ravendb/ravendb:4.0.3-ubuntu.16.04-x64
    environment:
      - RAVEN_ARGS=-n -l
      - RAVEN_Setup.Mode=Unsecured
      - RAVEN_License.Eula.Accepted=true
      - RAVEN_RunInMemory=true
      - UNSECURED_ACCESS_ALLOWED=PublicNetwork
    ports:
      - 8080:8080
