version: '3.3'

services:
  commandhandling_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.CommandHandling.Test
    entrypoint: dotnet 
    command: test
    
  eventhandling_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.EventHandling.Test
    entrypoint: dotnet
    command: test

  eventsourcing_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.EventSourcing.Test
    entrypoint: dotnet
    command: test

  example:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    depends_on:
      - eventstore
      - ravendb
    ports:
      - 5000:5000
    environment:
      - EVENTSTORE_HOST=eventstore
      - RAVENDB_HOST=http://ravendb:8080
    working_dir: /spray/src/SprayChronicle.Example
    entrypoint: dotnet
    command: run

  example_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Example.Test
    entrypoint: dotnet
    command: test

  messagehandling_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.MessageHandling.Test
    entrypoint: dotnet
    command: test

  persistence_mongo_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Persistence.Mongo.Test
    entrypoint: dotnet
    command: test

  persistence_ouro_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Persistence.Ouro.Test
    depends_on:
      - eventstore
    environment:
      - EVENTSTORE_HOST=eventstore
    entrypoint: dotnet
    command: test

  persistence_raven_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Persistence.Raven.Test
    depends_on:
      - ravendb
    environment:
      - RAVENDB_HOST=http://ravendb:8080
    entrypoint: dotnet
    command: test

  queryhandling_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.QueryHandling.Test
    entrypoint: dotnet
    command: test

  server_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Server.Test
    entrypoint: dotnet
    command: test

  server_http_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Server.Http.Test
    entrypoint: dotnet
    command: test

  testing_test:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./:/spray
    working_dir: /spray/test/SprayChronicle.Testing.Test
    entrypoint: dotnet test
    command: test

  eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_MEM_DB=1
      - EVENTSTORE_START_STANDARD_PROJECTIONS=1
      - EVENTSTORE_RUN_PROJECTIONS=All
    ports:
      - 1113:1113
      - 2113:2113

  ravendb:
    image: ravendb/ravendb:4.0.3-ubuntu.16.04-x64
    environment:
      - RAVEN_ARGS=-n -l --Setup.Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_RunInMemory=true
    ports:
      - 8080:8080
