docker-compose up --abort-on-container-exit commandhandling
docker-compose up --abort-on-container-exit eventhandling
docker-compose up --abort-on-container-exit eventsourcing
docker-compose up --abort-on-container-exit example
docker-compose up --abort-on-container-exit messagehandling
docker-compose up --abort-on-container-exit persistence_mongo
docker-compose up --abort-on-container-exit persistence_ouro
docker-compose up --abort-on-container-exit persistence_raven
docker-compose up --abort-on-container-exit queryhandling
docker-compose up --abort-on-container-exit server
docker-compose up --abort-on-container-exit server_http
docker-compose up --abort-on-container-exit testing
